test : 
	python main.py < ../tests/inputs/alternating.txt > output_alternating.txt
	python main.py < ../tests/inputs/ones.txt > output_ones.txt
	python main.py < ../tests/inputs/zeros.txt > output_zeros.txt
	python main.py < ../tests/inputs/freq_data.txt > output_freq_data.txt