test : 
	python main.py < ./a.out < ../io/sample.in.1 > output_alternating.txt
	python main.py < ./a.out < ../io/sample.in.2 > output_ones.txt
	python main.py < ./a.out < ../io/sample.in.3 > output_zeros.txt
	python main.py < ./a.out < ../io/sample.in.4 > output_freq_data.txt